In [5]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [8]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [10]:
# Checking dimension of the tensor (ndim - number of dimensions)
scalar.ndim

0

In [12]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [14]:
# Checking dimension of vector
vector.ndim

1

In [16]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [18]:
# Checking dimension of matrix
matrix.ndim

2

In [23]:
from numpy import dtype
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype = tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [26]:
# Checkinng dimension of another_matrix
another_matrix.ndim

2

In [28]:
# Lets create a tensor.
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [15, 16, 17]]])
tensor
# Inside the main list we have lists totally 3 and inside each of these we again have 2 lists and inside of these lists we have 3 items.
# You can understand it like that.

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [15, 16, 17]]], dtype=int32)>

In [30]:
# Checking dimension of tensor
tensor.ndim

3